### ISSUE TITLE
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0)

### ISSUE THREAD

**Issue by ayyucedemirbas** [ageitgey/face_recognition#233] opened 2017-11-12 18:56 UTC
* face_recognition version:
* Python version: 3.5.2
* Operating System: Ubuntu

### Description

I am trying to compile this program:

https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam_faster.py

but I got:

OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/imgwarp.cpp, line 3483 Traceback (most recent call last): File "face.py", line 31, in small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25) cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:3483: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

error message.

**Comment by ageitgey** [comment] 2017-11-13 00:49
Basically that means OpenCV wasn't able to grab an image from your webcam. Either you don't have a webcam hooked up or OpenCV isn't configured to be able to access it. So you'll have to figure out why OpenCV can't access your webcam.

**Comment by alundiak** [comment] 2017-12-06 10:53
@ageitgey 
> OpenCV isn't configured to be able to access it.

What special config it might be? Any suggestions?

**Comment by ageitgey** [comment] 2017-12-06 17:44
I wish I had a better answer, but the best I can say is to check OpenCV's github and related forums. There are huge variety of operating systems, video cameras and ways of compiling OpenCV and I can't really help debug OpenCV installation issues since I don't know all the answers for every platform.

The goal of using OpenCV there in the demo program is just to grab an image from your webcam and load it into a numpy array. If you can find some other library or solution for doing that which works on you computer, it should work just as well as a replacement.

Again, I wish I had a better answer to help you fix it. But I don't know what's wrong specifically on your system with OpenCV and it's not really a problem with face_recognition, so I'm not sure how to help.

Closing this since it's a duplicate of #191

**Closed by ageitgey** 2017-12-06 17:44 UTC

**Comment by gayathri4198** [comment] 2019-09-27 16:02
error: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize
i have got this error..in the line => image = cv2.resize(image, fixed_size)
how can i fix this error..can somebody help me out

**Comment by shubhamias12** [comment] 2022-03-31 04:06
**The code is reading the .tif pics better but when it coming to jpg coming this error can anyone help** 

E:\codiiiing\anna\envs\myenv1\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
E:\codiiiing\anna\envs\myenv1\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])E:\codiiiing\anna\envs\myenv1\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])E:\codiiiing\anna\envs\myenv1\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])E:\codiiiing\anna\envs\myenv1\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])E:\codiiiing\anna\envs\myenv1\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp, line 3289
Traceback (most recent call last):
  File "e:/Dissertation/coding/skin lession/DC-UNet-main/DC-UNet-main/main.py", line 30, in <module>
    resized_img = cv2.resize(img,(256, 192), interpolation = cv2.INTER_CUBIC)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3289: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize
