### ISSUE TITLE
pip2 install MemoryError

### ISSUE THREAD

**Issue by lambaaada** [ageitgey/face_recognition#18] opened 2017-03-18 19:23 UTC
* face_recognition version:  b10c119
* Python version: 2.7
* Operating System: windows 7

I tried the cmd command:
 pip2 install face_recognition
before downloading the files here in github and moving to the python2.7 path,
and got a MemoryError once the process reached 99%.

Tried again after doing all of the above and got the exact same results:

![memoryerror](https://cloud.githubusercontent.com/assets/26509613/24075293/2161beda-0c21-11e7-8eaf-ed604d7b977f.jpg)

**Comment by ageitgey** [comment] 2017-03-19 01:28
I think the issue is the file is too big for your available pip cache memory.

Can you try `pip2 --no-cache-dir install face_recognition` instead and see if that fixes the issue?

**Comment by lambaaada** [comment] 2017-03-19 15:42
Thanks I tried it and it continued onward!
Though now I am experiencing a different error, despite already downloading cmake.
![err2](https://cloud.githubusercontent.com/assets/26509613/24082270/67e17fc6-0ccb-11e7-8bf8-c5830b22c00d.jpg)

**Comment by ageitgey** [comment] 2017-03-19 20:27
This issue is not about `cmake` itself. It's that `dlib` is failing to compile because it can't find a c++ compiler on your system.

I've never compiled `dlib` myself on Windows, so I can't really help you unfortunately. You might check the dlib docs at http://dlib.net. It probably involves installing [Visual Studio](https://www.visualstudio.com/downloads/), installing boost-python, and then compiling dlib. Sorry I don't have an easier answer.

**Comment by lambaaada** [comment] 2017-03-20 15:46
I have been having quite alot of trouble trying to fix it from various computers, with help from what you said...Thanks for the help though!

Also could I possibly get dlib to work it's configuration problems and all that via https://github.com/Microsoft/vcpkg
?

I also am having quite alot of trouble getting vcpkg to work too...

**Comment by ageitgey** [comment] 2017-03-20 17:25
Like I said in the project README, I haven't tested this library on Windows at all. I've only tested it on macOS and Linux. I don't have a machine with Windows, so unfortunately I can't help. Sorry about that.

**Comment by ageitgey** [comment] 2017-03-21 20:16
Closing this issue since the original issue in the title is fixed. But I'm sorry I don't have better advice yet for installing on Windows.

**Closed by ageitgey** 2017-03-21 20:16 UTC

**Comment by ras0219-msft** [comment] 2017-03-22 23:47
@lambaaada Could you open an issue on https://github.com/microsoft/vcpkg with your Dlib issue? We'd be happy to fix it!

**Comment by Gillu13** [comment] 2017-08-12 15:10
@lambaaada Just a thought here: it seems that you already had dlib installed on your system and that it was uninstalled while using pip... As a workaround, do you think it would help (after having reinstalled dlib from where you installed it in the first place) to clone the face_recognition repo, to edit the setup.py file removing dlib from the requirements list, then run `python setup.py install` in a terminal?
